secretGenerator:
- name: mysql-pass
  literals:
  - password=123qwe!
resources:
- mysql-pvc.yaml
- mysql-deployment.yaml
- mysql-service.yaml
- wordpress-pvc.yaml
- wordpress-deployment.yaml
- wordpress-service.yaml
- wordpress-route.yaml 
- tho-route.yaml